<%@ Page Title="" Language="C#" MasterPageFile="~/Master.Master" AutoEventWireup="true" CodeBehind="agr_search.aspx.cs" Inherits="Portal.agr_search" %>
<asp:Content ID="Content1" ContentPlaceHolderID="Navigation" runat="server">
    <ul id="Navigator" runat="server"></ul>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <style>
        .ComponentCell {
            width: 65%;
            padding: 5px;
        }
        .LabelCell {
            padding: 5px;
            width: 35%;
        }
        #SectionContainer1 {
            width: 40%;
        }
    </style>
<form id="form1" runat="server">
    <asp:Panel ID="agr_srch_Section" Visible="true" runat="server">     
            <asp:ScriptManager ID="scrptmnger" runat="server"></asp:ScriptManager>
            <asp:UpdatePanel ID="updpnl" runat="server" ChildrenAsTriggers="true">
                <ContentTemplate>
                    <table id="SectionContainer1" runat="server">
                        <tr runat="server">
                            <td class="LabelCell">Avtalstyp</td>
                            <td class="ComponentCell">
                                <asp:DropDownList ID="dll_AgreementType" runat="server" Width="100%"></asp:DropDownList>
                            </td>
                        </tr>
                        <tr>
                            <td class="LabelCell">Division </td>
                            <td class="ComponentCell">
                                <asp:DropDownList ID="dll_Company_Division" runat="server" Width="100%"></asp:DropDownList>
                            </td>
                        </tr>
                        <tr>
                            <td class="LabelCell">Partnernummer: </td>
                            <td class="ComponentCell" runat="server" id="partNum_txtBox_Container">
                                <asp:TextBox ID="businessPartner_txtBox" runat="server" Text="*"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="LabelCell">Namn: </td>
                            <td class="ComponentCell" runat="server" id="namn_txtBox_Container">
                                <asp:TextBox ID="namn_txtBox" runat="server" Text="*"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="LabelCell">Org.nr:</td>
                            <td class="ComponentCell" runat="server" id="org_Nr_txtBox_Container">
                                <asp:TextBox ID="orgNr_txtBox" runat="server" Text="*"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="LabelCell">Avtalsnr:</td>
                            <td class="ComponentCell" runat="server" id="avtals_Nr_txtBox_Container">
                                <asp:TextBox ID="agreementNr_txtBox" runat="server" Text="*"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="LabelCell">Avtalsansvarig:</td>
                            <td class="ComponentCell" runat="server" id="avtals_Ansv_txtBox_Container">
                                <asp:TextBox ID="agreementResponsible_txtBox" runat="server" Text="*"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="LabelCell">Avdelning:</td>
                            <td class="ComponentCell" runat="server" id="avdelning_txtBox_Container">
                                <asp:TextBox ID="department_txtBox" runat="server" Text="*"></asp:TextBox>
                            </td>
                        </tr>
                    </table>
                    <asp:Button runat="server" ID="SokAvtal_btn" Text="Sök avtal" OnClick="SokAvtal_btn_Click" />
                    <asp:Button runat="server" ID="aterstall_btn" Text="Återställ" />
                    <br />
                    <br />
                    <asp:Panel ID="pnl" runat="server">
                        <asp:DropDownList runat="server" ID="DDL_Create_Agr"></asp:DropDownList>
                        <asp:DropDownList runat="server" ID="DDL_Create_DIV" name="ddl_Create_DIV"></asp:DropDownList>
                        <asp:Button runat="server" ID="Create_btn" Text="Skapa nytt avtal" OnClick="Create_btn_Click" />
                    </asp:Panel>
                    <asp:GridView ID="gv_Result" runat="server" AutoGenerateDeleteButton="true" AutoGenerateEditButton="false" ShowFooter="true" OnRowDeleting="gv_Result_RowDeleting"></asp:GridView>
                </ContentTemplate>
                <Triggers>
                    <asp:AsyncPostBackTrigger ControlID="gv_Result" EventName="RowDeleting" />
                </Triggers>
            </asp:UpdatePanel>
    </asp:Panel>
   
   </form>
</asp:Content>
